### ISSUE TITLE
Fixing previously unconventional version

### ISSUE THREAD

**Issue by IniZio** [Updater/semantic-release-monorepo#17]
I tried to migrate my repo to using semantic-release-monorepo from just `autopublish`. However since previously the packages were commited manually, I need to fix the tags to match the HEAD commit. However not really sure what tag name should i push to fix each package?

Would be grateful if given an example!

**Comment by pmowrer** [comment]
Sure thing! The expected format is `npm` package name, a dash and the regular npm version tag. 

E.g.:

`semantic-release-monorepo-v.4.0.2`

Does that help?

**Comment by IniZio** [comment]
Thanks for the reply! Yes i did try it, for instance one of my packages is called 'generator-clipped-base' and the latest version before i migrated to semantic-release-monorepo is 0.1.3, so i force pushed 'generator-clipped-base-v0.1.3' tag.

However it still gives the message 'The commit the last release of this package was derived from cannot be determined from the release metadata nor from the repository tags.' So I think it did not recognize the namespaced tag?

**Comment by pmowrer** [comment]
That looks right to me. Not sure what is going on, but I think perhaps the debugging logs might shed some light. 

```bash
semantic-release -e semantic-release-monorepo --debug
```

There'll be a lot of output, but somewhere in there you should find a stretch of logs like this:

```
[Semantic release]: Call plugin get-last-release
info attempt registry request try #1 at 22:57:07
http request GET https://registry.npmjs.org/@updater%2Fui-strikethrough
http 200 https://registry.npmjs.org/@updater%2Fui-strikethrough
[Semantic release]: Found version 1.0.1 of package @updater/ui-strikethrough with dist-tag latest
  semantic-release:get-version-head Error: Command failed: git rev-list -1 v@updater/ui-strikethrough-v1.0.1
  semantic-release:get-version-head fatal: ambiguous argument 'v@updater/ui-strikethrough-v1.0.1': unknown revision or path not in the working tree.
  semantic-release:get-version-head Use '--' to separate paths from revisions, like this:
  semantic-release:get-version-head 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:get-version-head 
  semantic-release:get-version-head 
  semantic-release:get-version-head     at Promise.all.then.arr (/home/ubuntu/angular-common/packages/strikethrough/node_modules/execa/index.js:236:11)
  semantic-release:get-version-head     at <anonymous>
  semantic-release:get-version-head     at process._tickCallback (internal/process/next_tick.js:188:7) +2s
  semantic-release:get-version-head Get git tag head +5ms
  semantic-release:get-version-head cmd: 'git rev-list -1 @updater/ui-strikethrough-v1.0.1' +1ms
  semantic-release:get-version-head stdout: 'f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-version-head Check if commit is in history +6ms
  semantic-release:get-version-head cmd: 'git merge-base --is-ancestor f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7 HEAD' +0ms
  semantic-release:get-version-head stdout: '' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-version-head Use tagHead: f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7 +0ms
  semantic-release:get-version-head Get git commit tag +6ms
  semantic-release:get-version-head cmd: 'git describe --tags --exact-match f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7' +0ms
  semantic-release:get-version-head stdout: '@updater/ui-strikethrough-v1.0.1' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-version-head Check if commit is in history +7ms
  semantic-release:get-version-head cmd: 'git merge-base --is-ancestor f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7 HEAD' +0ms
  semantic-release:get-version-head stdout: '' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-version-head Use gitHead: f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7 +13ms
  semantic-release:get-version-head Get git commit tag +6ms
  semantic-release:get-version-head cmd: 'git describe --tags --exact-match f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7' +0ms
  semantic-release:get-version-head stdout: '@updater/ui-strikethrough-v1.0.1' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
[Semantic release]: Retrieving commits since f8f8a5f1695264e2d9cc0103c4f3a3a01e42afe7, corresponding to version 1.0.1
[Semantic release]: Found 23 commits since last release
```

I'd be curious to see what it looks like in your case.

**Comment by IniZio** [comment]
the script i run to publish is `$(npm config get prefix)/bin/lerna exec --concurrency 1 semantic-release -e semantic-release-monorepo`

the log of travis for a package is 
```
lerna info version 2.5.1
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin verifyConditions from @semantic-release/condition-travis
[Semantic release]: Load plugin getLastRelease from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Travis Deploy Once]: There is only one job for this build.
[Semantic release]: Call plugin get-last-release
info attempt registry request try #1 at 04:50:41
http request GET https://registry.npmjs.org/generator-clipped-base
http 200 https://registry.npmjs.org/generator-clipped-base
[Semantic release]: Found version 0.1.3 of package generator-clipped-base with dist-tag latest
[Semantic release]: The commit the last release of this package was derived from cannot be determined from the release metadata nor from the repository tags.
This means semantic-release can not extract the commits between now and then.
This is usually caused by releasing from outside the repository directory or with innaccessible git metadata.
You can recover from this error by creating a tag for the version "0.1.3" on the commit corresponding to this release:
$ git tag -f v0.1.3 <commit sha1 corresponding to last release>
$ git push -f --tags origin master
[Semantic release]: ENOGITHEAD There is no commit associated with last release
```

**Comment by pmowrer** [comment]
I think you're right in that it's not getting loaded. What version of `semantic-release` are you using?

**Comment by IniZio** [comment]
11.1.0

**Comment by pmowrer** [comment]
Strange, that should work. Maybe the `-e` options is being dropped somehow because of the way `lerna exec` is called? It's supposed to [need `--` when passing flags](https://github.com/lerna/lerna#exec). Have you tried:

```bash
lerna exec --concurrency 1 -- npx semantic-release -e -semantic-release-monorepo
```

**Comment by IniZio** [comment]
Hmm if i use you command `lerna exec --concurrency 1 -- npx semantic-release -e semantic-release-monorepo`, it will return error that 
```
Error: Cannot find module 'semantic-release/lib/get-version-head'
```

**Comment by pmowrer** [comment]
The file `semantic-release/lib/get-version-head` was removed as `semantic-release` 11.2.0 which is why this package is currently locked into version 11.1.0. Hoping to get a fix out for this today.

I think running `semantic-release` without `npx` would require `semantic-release` to have be installed globally (`npm i -g`). With `npx`, it will install `semantic-release` for you (always latest version though) unless it's present locally.

**Comment by IniZio** [comment]
I successfully ran the command by updating devdependencies, but it seems the tag that I set specific to the package and its latest version is not recognised

The debug message shows that semantic release tried to find 0.1.3 tag but failed

**Comment by pmowrer** [comment]
What does the `--debug` output look like?

**Comment by pmowrer** [comment]
PS Just made a patch version to fix compatibility with `semantic-release` 11.2.0 and above (through latest)

**Comment by IniZio** [comment]
So weird it just keep trying to get the version head right from semantic-release instead of from semantic-release-monorepo, 
```
2018-01-05T02:40:35.963Z semantic-release:get-version-head Check if the current working directory is a git repository
2018-01-05T02:40:35.965Z semantic-release:get-version-head cmd: 'git rev-parse --git-dir'
2018-01-05T02:40:35.965Z semantic-release:get-version-head stdout: '/home/travis/build/clippedjs/clipped/.git'
2018-01-05T02:40:35.965Z semantic-release:get-version-head stderr: ''
2018-01-05T02:40:35.965Z semantic-release:get-version-head code: 0
2018-01-05T02:40:36.175Z semantic-release:config options values: [ 'branch',
  'repositoryUrl',
  'analyzeCommits',
  'generateNotes',
  'getLastRelease',
  'publish',
  'debug',
  'dryRun' ]
2018-01-05T02:40:36.175Z semantic-release:config name: undefined
2018-01-05T02:40:36.175Z semantic-release:config branch: 'master'
2018-01-05T02:40:36.175Z semantic-release:config repositoryUrl: 'https://github.com/clippedjs/clipped.git'
2018-01-05T02:40:36.175Z semantic-release:config analyzeCommits: [AsyncFunction]
2018-01-05T02:40:36.175Z semantic-release:config generateNotes: [AsyncFunction]
2018-01-05T02:40:36.175Z semantic-release:config verifyConditions: undefined
2018-01-05T02:40:36.175Z semantic-release:config verifyRelease: undefined
2018-01-05T02:40:36.175Z semantic-release:config publish: [ [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction],
  [AsyncFunction] ]
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin verifyConditions from @semantic-release/condition-travis
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin get-last-release
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
info attempt registry request try #1 at 02:40:38
http request GET https://registry.npmjs.org/generator-clipped-base
http 200 https://registry.npmjs.org/generator-clipped-base
[Semantic release]: Found version 0.1.3 of package generator-clipped-base with dist-tag latest
2018-01-05T02:40:38.224Z semantic-release:npm Error: Command failed: git rev-list -1 v0.1.3
fatal: ambiguous argument 'v0.1.3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at Promise.all.then.arr (/home/travis/build/clippedjs/clipped/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-01-05T02:40:38.231Z semantic-release:npm Error: Command failed: git rev-list -1 0.1.3
fatal: ambiguous argument '0.1.3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at Promise.all.then.arr (/home/travis/build/clippedjs/clipped/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-01-05T02:40:38.661Z semantic-release:npm Error: Command failed: git rev-list -1 v0.1.3
fatal: ambiguous argument 'v0.1.3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at Promise.all.then.arr (/home/travis/build/clippedjs/clipped/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-01-05T02:40:38.667Z semantic-release:npm Error: Command failed: git rev-list -1 0.1.3
fatal: ambiguous argument '0.1.3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at Promise.all.then.arr (/home/travis/build/clippedjs/clipped/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Semantic release]: The commit the last release of this package was derived from cannot be determined from the release metadata nor from the repository tags.
This means semantic-release can not extract the commits between now and then.
This is usually caused by releasing from outside the repository directory or with innaccessible git metadata.
You can recover from this error by creating a tag for the version "0.1.3" on the commit corresponding to this release:
$ git tag -f v0.1.3 <commit sha1 corresponding to last release>
$ git push -f --tags origin master
[Semantic release]: ENOGITHEAD There is no commit associated with last release
```
But my command did run successfully
```
$(npm config get prefix)/bin/lerna exec --concurrency 1 -- npx semantic-release@11.1.0 -e semantic-release-monorepo --debug --dry-run
```
It is definitely my problem rather than issues with semantic-release-monorepo, it does not seem I did anything special to cause it to fail... :thinking:

**Comment by pmowrer** [comment]
Not sure what's going on here. Doesn't look like `semantic-release-monorepo`'s fallback lookup is being applied. There was a fix for a scenario like that in `4.0.2`. I'm going to add some more logging, including version information, to aid in debugging.

**Comment by IniZio** [comment]
I think it actually did apply the fallback lookup, which is why in the log we see `git rev-list -1 v0.1.3` and `git rev-list -1 0.1.3`. The first one is from semantic-release, the second one is semantic-release-monorepo. It seems that monorepo did not apply the notice that it is a package.

Also one really interesting thing is that i moved the root package 'clipped' into 'packages/clipped' folder, and running the command on it actually works perfectly fine, it did find 'clipped-v1.7.2' and calculated number of commits since last release.

**Comment by pmowrer** [comment]
The fallback is supposed to be `<package-name>-v<version>`, not just `v<version>`.

Great to hear `packages/clipped` works! What are the ones that don't?

**Comment by IniZio** [comment]
they are in different folders, like `presets/docker`, `generators/base`, but even if i put them in `packages/docker` for example it still does not work

**Comment by IniZio** [comment]
Also they are all using same `semantic-release` and `semantic-release-monorepo` version

**Comment by pmowrer** [comment]
Try version `4.1.0`. It will log the version being used for each plugin (when passing `--debug`). It should help shed some more light on what's going on. 

You should see a line like this:
```bash
[Semantic release]: Call plugin get-last-release
  semantic-release:monorepo Running 'getLastRelease' version '4.1.0' +0ms
```

**Comment by IniZio** [comment]
Hmm there are differences between using the plugin with `-e semantic-release-monorepo` and not using it. 

https://www.diffchecker.com/wryZprJA has the difference. Left side is when not using semantic-release-monorepo, the right side is when adding the option value. However `semantic-release:monorepo Running 'getLastRelease' version '4.1.0'` did not appear.

**Comment by pmowrer** [comment]
> Hmm there are differences between using the plugin with -e semantic-release-monorepo and not using it.

That is expected. If you run without this option, you're just running "regular" `semantic-release`. With `-e semantic-release-monorepo`, you're applying the `semantic-release-monorepo` set of plugins. 

> However semantic-release:monorepo Running 'getLastRelease' version '4.1.0' did not appear.
This means you're not actually using `semantic-release-monorepo` 4.1.0 (and perhaps a version earlier than 4.0.2, which would explain why its not working properly).

Be sure that each package in your `lerna` repo have `semantic-release` and `semantic-release-monorepo` installed with their latest versions.

**Comment by IniZio** [comment]
Yes, they do all have `semantic-release` and `semaentic-release-monorepo` installed with `lerna add --dev`, and the command did apply the plugin i believe from the logs

**Comment by pmowrer** [comment]
The critical part is making sure the right version of the tools are installed. If you don't see the debugging message mentioned above, you don't have right version installed and things won't work. 

I think `lerna` is a great tool, but in this instance it might be easier from a debugging standpoint to focus on a particular package and install the dependencies manually until you've got it working. 

```bash
npm i -D semantic-release@next semantic-release-monorepo

...

+ semantic-release-monorepo@4.1.0
+ semantic-release@12.2.0
```

**Comment by IniZio** [comment]
But it did appear in those packages that did not work, so in fact the plugin did execute, just not actually finding the tag head?

**Comment by IniZio** [comment]
Weird i tried a hack, by force pushing tag v1.8.0 to github and publish all the packages as that version, so that they will treat that as tag head.

`semantic-release-monorepo` found the taghead and published for each package successfully as `package-version`. but then if i bump a fake feature commit, they still try to look for 'v1.9.0' instead of `package-v1.9.0`.

**Comment by pmowrer** [comment]
> But it did appear in those packages that did not work, so in fact the plugin did execute, just not actually finding the tag head?

Sorry about the confusion, I missed the debug statement in the right side of your diff! I think I've found the problem and hoping to get a fix out today.

**Comment by IniZio** [comment]
Thanks a lot for your help! :pray:

**Comment by pmowrer** [comment]
Here's my theory:

When running locally with `--dry-run`, your local repository isn't up-to-date with origin's git tags (e.g. `package-v1.9.0` exists on origin but not locally because you haven't run `git fetch --tags` recently). The default fallback mechanism in `semantic-release` doesn't cover this scenario (or even help you understand the problem), maybe because the authors are very intent on designing `semantic-release` to only cover CI scenarios (even though there's `--dry-run`).

Just released `4.2.0`, which adds fetching git tags as part of the fallback. It also fixes and improves some of the debugging information (so if my theory is wrong, at least we can maybe help narrow down the problem further). Let me know how it goes!

**Comment by pmowrer** [comment]
What's the rest of the output? There's should be additional logging statements by `semantic-release:monorepo` as of `4.2.0`...

**Comment by IniZio** [comment]
The log is as follows
```
  semantic-release:get-version-head Check if the current working directory is a git repository +0ms
  semantic-release:get-version-head cmd: 'git rev-parse --git-dir' +1ms
  semantic-release:get-version-head stdout: '/home/iniz/magic/clippedjs/clipped-dev/.git' +1ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:config options values: [ 'branch',
  semantic-release:config   'repositoryUrl',
  semantic-release:config   'analyzeCommits',
  semantic-release:config   'generateNotes',
  semantic-release:config   'getLastRelease',
  semantic-release:config   'publish',
  semantic-release:config   'debug',
  semantic-release:config   'dryRun' ] +0ms
  semantic-release:config name: undefined +0ms
  semantic-release:config branch: 'master' +1ms
  semantic-release:config repositoryUrl: 'git+https://github.com/clippedjs/clipped.git' +0ms
  semantic-release:config analyzeCommits: [AsyncFunction] +0ms
  semantic-release:config generateNotes: [AsyncFunction] +0ms
  semantic-release:config verifyConditions: undefined +0ms
  semantic-release:config verifyRelease: undefined +0ms
  semantic-release:config publish: [ [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction] ] +0ms
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin verifyConditions from @semantic-release/condition-travis
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin get-last-release
  semantic-release:monorepo Running 'getLastRelease' version '4.2.0' +0ms
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
info attempt registry request try #1 at 11:00:25
http request GET https://registry.npmjs.org/clipped-preset-docker
http 200 https://registry.npmjs.org/clipped-preset-docker
[Semantic release]: Found version 1.9.0 of package clipped-preset-docker with dist-tag latest
  semantic-release:npm Error: Command failed: git rev-list -1 v1.9.0
  semantic-release:npm fatal: ambiguous argument 'v1.9.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at Promise.all.then.arr (/home/iniz/magic/clippedjs/clipped-dev/node_modules/execa/index.js:236:11)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
  semantic-release:npm Error: Command failed: git rev-list -1 1.9.0
  semantic-release:npm fatal: ambiguous argument '1.9.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at Promise.all.then.arr (/home/iniz/magic/clippedjs/clipped-dev/node_modules/execa/index.js:236:11)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:188:7) +9ms
  semantic-release:npm Error: Command failed: git rev-list -1 v1.9.0
  semantic-release:npm fatal: ambiguous argument 'v1.9.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at Promise.all.then.arr (/home/iniz/magic/clippedjs/clipped-dev/node_modules/execa/index.js:236:11)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:188:7) +17ms
  semantic-release:npm Error: Command failed: git rev-list -1 1.9.0
  semantic-release:npm fatal: ambiguous argument '1.9.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at Promise.all.then.arr (/home/iniz/magic/clippedjs/clipped-dev/node_modules/execa/index.js:236:11)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:188:7) +7ms
[Semantic release]: The commit the last release of this package was derived from cannot be determined from the release metadata nor from the repository tags.
This means semantic-release can not extract the commits between now and then.
This is usually caused by releasing from outside the repository directory or with innaccessible git metadata.

You can recover from this error by creating a tag for the version "1.9.0" on the commit corresponding to this release:
$ git tag -f v1.9.0 <commit sha1 corresponding to last release>
$ git push -f --tags origin master
```
dead silence from monorepo actually...

**Comment by pmowrer** [comment]
It looks like `@semantic-release/npm` version `2.6.1` that was released the other day may be the culprit. Due to an internal change,  `semantic-release-monorepo` is unable to wrap it ([issue](https://github.com/semantic-release/npm/issues/36)). 

Unfortunately, both `semantic-release` versions 11 and 12 have a minor version (`^2.0.0`) dependency on `@semantic-release/npm`. For now, you should be able to work around it by manually installing an earlier version of `@semantic-release/npm`, but its obviously less than an ideal workaround going forward. Hopefully the maintainers of `semantic-release` are open to finding a solution.

**Comment by IniZio** [comment]
Seems like that is the reason, thanks so much for your patience updating on the issue :pray:.

Since semantic-release is working on proposal for monorepo (https://github.com/semantic-release/semantic-release/issues/193), I will use the the workaround or just manually publish for now, hopefully that official monorepo support will come soon!
