### ISSUE TITLE
Issue encountered with "ENOGITHEAD There is no commit associated with last release"

### ISSUE THREAD

**Issue by joshblack** [Updater/semantic-release-monorepo#22]
Hi there! 👋  love this project! Unfortunately, ran into an issue when trying to do the following command in a `lerna`-based project, specifically:

```bash
$(yarn bin)/lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo
```

When running in `debug` mode, the output looks great until we get to `semantic-release:npm` which is trying to find `v1.0.0` of a specific package. However, instead of finding `<packageName>-v1.0.0` it's reporting the following:

```bash
[Semantic release]: Found version 1.0.0 of package @spec/babel-preset-spec with dist-tag latest
  semantic-release:npm Error: Command failed: git rev-list -1 v1.0.0
  semantic-release:npm fatal: ambiguous argument 'v1.0.0': unknown revision or path not in the working tree.
```

Here is the full debug information if that's helpful:

<details>
<summary>Semantic Release Debug</summary>

```bash
$ $(yarn bin)/lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo --debug                                                                             3.33s
lerna info version 2.7.0
lerna info versioning independent
[Semantic release]: This run was not triggered in a known CI environment, running in dry-run mode.
  semantic-release:get-version-head Check if the current working directory is a git repository +0ms
  semantic-release:get-version-head cmd: 'git rev-parse --git-dir' +0ms
  semantic-release:get-version-head stdout: '/Users/joshuablack/oss/spec/.git' +1ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:config options values: [ 'branch',
  semantic-release:config   'repositoryUrl',
  semantic-release:config   'analyzeCommits',
  semantic-release:config   'generateNotes',
  semantic-release:config   'getLastRelease',
  semantic-release:config   'publish',
  semantic-release:config   'ci',
  semantic-release:config   'debug',
  semantic-release:config   'dryRun' ] +0ms
  semantic-release:config name: undefined +0ms
  semantic-release:config branch: 'master' +0ms
  semantic-release:config repositoryUrl: 'https://github.com/joshblack/spec/tree/master/packages/babel-preset-spec' +0ms
  semantic-release:config analyzeCommits: [AsyncFunction] +0ms
  semantic-release:config generateNotes: [AsyncFunction] +1ms
  semantic-release:config verifyConditions: undefined +0ms
  semantic-release:config verifyRelease: undefined +0ms
  semantic-release:config publish: [ [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction],
  semantic-release:config   [AsyncFunction] ] +0ms
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Verify GitHub authentication
[Semantic release]: Call plugin get-last-release
  semantic-release:monorepo Running 'getLastRelease' version '4.2.0' +0ms
info attempt registry request try #1 at 10:16:53
http request GET https://registry.npmjs.org/@spec%2Fbabel-preset-spec
http 200 https://registry.npmjs.org/@spec%2Fbabel-preset-spec
[Semantic release]: Found version 1.0.0 of package @spec/babel-preset-spec with dist-tag latest
  semantic-release:npm Error: Command failed: git rev-list -1 v1.0.0
  semantic-release:npm fatal: ambiguous argument 'v1.0.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at makeError (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:169:9)
  semantic-release:npm     at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:274:16)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:160:7) +0ms
  semantic-release:npm Error: Command failed: git rev-list -1 1.0.0
  semantic-release:npm fatal: ambiguous argument '1.0.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at makeError (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:169:9)
  semantic-release:npm     at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:274:16)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:160:7) +6ms
  semantic-release:npm Error: Command failed: git rev-list -1 v1.0.0
  semantic-release:npm fatal: ambiguous argument 'v1.0.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at makeError (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:169:9)
  semantic-release:npm     at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:274:16)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:160:7) +14ms
  semantic-release:npm Error: Command failed: git rev-list -1 1.0.0
  semantic-release:npm fatal: ambiguous argument '1.0.0': unknown revision or path not in the working tree.
  semantic-release:npm Use '--' to separate paths from revisions, like this:
  semantic-release:npm 'git <command> [<revision>...] -- [<file>...]'
  semantic-release:npm
  semantic-release:npm
  semantic-release:npm     at makeError (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:169:9)
  semantic-release:npm     at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/@semantic-release/npm/node_modules/execa/index.js:274:16)
  semantic-release:npm     at <anonymous>
  semantic-release:npm     at process._tickCallback (internal/process/next_tick.js:160:7) +6ms
[Semantic release]: The commit the last release of this package was derived from cannot be determined from the release metadata nor from the repository tags.
This means semantic-release can not extract the commits between now and then.
This is usually caused by releasing from outside the repository directory or with innaccessible git metadata.

You can recover from this error by creating a tag for the version "1.0.0" on the commit corresponding to this release:
$ git tag -f v1.0.0 <commit sha1 corresponding to last release>
$ git push -f --tags origin master

[Semantic release]: ENOGITHEAD There is no commit associated with last release
lerna ERR! exec Errored while executing 'semantic-release -e semantic-release-monorepo --debug' in '@spec/babel-preset-spec'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: semantic-release -e semantic-release-monorepo --debug
lerna ERR!     at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: semantic-release -e semantic-release-monorepo --debug
    at Promise.all.then.arr (/Users/joshuablack/oss/spec/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'semantic-release -e semantic-release-monorepo --debug',
  timedOut: false,
  exitCode: 1
```
</details>

<br>

And below are the following relevant package versions as well:

```json
{
    "lerna": "^2.7.0",
    "semantic-release": "^12.2.2",
    "semantic-release-monorepo": "^4.2.0"
}
```

---

Was hopeful that you all could steer me in the right direction here to figure out what's going on. Thanks again for this project! Can't wait to get it working again 😄

**Comment by pmowrer** [comment]
Hi @joshblack! 

Hopefully we should be able to get you right back on track! 

Likely, the problem you're experiencing is due to a change in `@semantic-release/npm` ([issue](https://github.com/semantic-release/npm/issues/36)), a default dependency of `semantic-release`. As of its version `2.6.1`, it's incompatible with `semantic-release-monorepo`. Since `semantic-release` depends on a minor version of it (`^2.0.0`), you likely have `2.6.1` or above installed. Creating a direct dependency on a version lower than `2.6.1` should resolve the problem:

```bash
yarn add -D @semantic-release/npm@2.6.0
```

I'm going to update the README and add a peer dependency on `@semantic-release/npm` <=2.6.1 today.
