### ISSUE TITLE
Reference Already Exists

### ISSUE THREAD

**Issue by bringking** [Updater/semantic-release-monorepo#54]
Thanks for this lib, it looks like just what we need for our monorepo project. However, we are running into an issue where two commits to two different packages in the same CI run are failing. Is this something that is supported? Here is the output from the release script - 

We are using Bolt to run a `release` command in each package - 

```
bolt ws run release
⚡️   bolt v0.20.7 (node v9.4.0)
[Semantic release]: Running semantic-release version 15.6.3
[Semantic release]: Running semantic-release version 15.6.3
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/github
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/github
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/github
[Semantic release]: Load plugin "success" from @semantic-release/github
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "fail" from @semantic-release/github
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/github
[Semantic release]: Load plugin "success" from @semantic-release/github
[Semantic release]: Load plugin "fail" from @semantic-release/github
[Semantic release]: Run automated release from branch chore/release-setup
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Run automated release from branch chore/release-setup
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: No git tag version found
[Semantic release]: No previous release found, retrieving all commits
[Semantic release]: Found 232 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: No git tag version found
[Semantic release]: No previous release found, retrieving all commits
[Semantic release]: Found 232 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Found 2 commits for package @ghostgroup/ui.analytics since last release
[Semantic release]: Analyzing commit: feat(component-analytics): add release

Add release script to analytics package
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: WIP for :eyes:
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 2 commits complete: minor release
[Semantic release]: There is no previous release, the next release version is 1.0.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Found 2 commits for package @ghostgroup/ui.analytics since last release
[Semantic release]: Call plugin prepare
[Semantic release]: Found 3 commits for package @ghostgroup/ui.animated-stars since last release
[Semantic release]: Analyzing commit: feat(component-animated-stars): release setup for animated stars
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: feat(component-analytics): add release

Add release script to analytics package
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: WIP for :eyes:
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 3 commits complete: minor release
[Semantic release]: There is no previous release, the next release version is 1.0.0
[Semantic release]: Wrote version 1.0.0 to package.json
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Create tag @ghostgroup/ui.analytics-v1.0.0
[Semantic release]: Found 3 commits for package @ghostgroup/ui.animated-stars since last release
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 1.0.0 to package.json
[Semantic release]: Create tag @ghostgroup/ui.animated-stars-v1.0.0
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.com/GhostGroup/ui.git HEAD:chore/release-setup
To https://github.com/GhostGroup/ui.git
 ! [remote rejected] @ghostgroup/ui.analytics-v1.0.0 -> @ghostgroup/ui.analytics-v1.0.0 (cannot lock ref 'refs/tags/@ghostgroup/ui.analytics-v1.0.0': reference already exists)
error: failed to push some refs to 'https://[secure]@github.com/GhostGroup/ui.git'


    at makeError (/home/ubuntu/ui/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/ubuntu/ui/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  stdout: '',
  stderr: 'To https://github.com/GhostGroup/ui.git\n ! [remote rejected] @ghostgroup/ui.analytics-v1.0.0 -> @ghostgroup/ui.analytics-v1.0.0 (cannot lock ref \'refs/tags/@ghostgroup/ui.analytics-v1.0.0\': reference already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/GhostGroup/ui.git\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.com/GhostGroup/ui.git HEAD:chore/release-setup',
  timedOut: false,
  killed: false }
{ Error: Command failed: git push --tags https://<redacted>@github.com/GhostGroup/ui.git HEAD:chore/release-setup
To https://github.com/GhostGroup/ui.git
 ! [remote rejected] @ghostgroup/ui.analytics-v1.0.0 -> @ghostgroup/ui.analytics-v1.0.0 (cannot lock ref 'refs/tags/@ghostgroup/ui.analytics-v1.0.0': reference already exists)
error: failed to push some refs to 'https://<redacted>@github.com/GhostGroup/ui.git'


    at makeError (/home/ubuntu/ui/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/ubuntu/ui/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  stdout: '',
  stderr: 'To https://github.com/GhostGroup/ui.git\n ! [remote rejected] @ghostgroup/ui.analytics-v1.0.0 -> @ghostgroup/ui.analytics-v1.0.0 (cannot lock ref \'refs/tags/@ghostgroup/ui.analytics-v1.0.0\': reference already exists)\nerror: failed to push some refs to \'https://<redacted>@github.com/GhostGroup/ui.git\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://<redacted>@github.com/GhostGroup/ui.git HEAD:chore/release-setup',
  timedOut: false,
  killed: false }
error Command failed with exit code 1.
error Error
error     at ChildProcess.child.on.code (/home/ubuntu/.config/yarn/global/node_modules/bolt/dist/modern/utils/processes.js:121:16)

bolt ws run release returned exit code 1

Action failed: bolt ws run release
```

Is there a configuration option I am missing or is this workflow not supported?

**Comment by pmowrer** [comment]
> an issue where two commits to two different packages in the same CI run are failing. Is this something that is supported? 

This is definitely supported! 

It's a bit difficult to follow the log you posted since logs of two `semantic-release` runs are interleaved, but it looks like the failure is due to the tag `@ghostgroup/ui.analytics-v1.0.0` already existing on the remote repository. I believe syncing the tags between the remote and local repositories is part of the `semantic-release` workflow, but perhaps try manually making sure tags are up-to-date locally (`git fetch --tags`).
