### ISSUE TITLE
Looks like it doesn't work with the latest semantic-release and plugins

### ISSUE THREAD

**Issue by stalniy** [Updater/semantic-release-monorepo#55]
It seems that from semantic-release version [15.8.0](https://github.com/semantic-release/semantic-release/releases) they changed some configuration options and updated own plugins to follow this. Every official semantic release plugin have a commit like this:

```
feat: use `cwd` and `env` options passed by core

BREAKING CHANGE: require `semantic-release` >= `15.8.0`
```

I think that's why `semantic-release-plugin-decorators` can't properly wrap new plugins and behavior

This is my log:

```
[8:56:26 AM] [semantic-release] › ℹ  Running semantic-release version 15.9.12
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github" in shareable config "../../tools/semantic-release"
[8:56:26 AM] [semantic-release] › ✔  Run automated release from branch master
[8:56:28 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:56:28 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[8:56:28 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[8:56:28 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[8:56:28 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[8:56:30 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[8:56:30 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:56:30 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:56:30 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[8:56:30 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[8:56:31 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[8:56:32 AM] [semantic-release] › ℹ  Found git tag @casl/react@0.7.2 associated with version 0.7.2
[8:56:32 AM] [semantic-release] › ℹ  Found 26 commits since last release
[8:56:32 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: ]"
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Found 18 commits for package @casl/react since last release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(package): get rid of local semantic-release dep
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: feat(react:can): updates typescript declarations
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: Revert "feat(react:can): updates typescript declarations"

This reverts commit 213dcde0286482aafc86e66a2ea0c49f630108f0.
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: feat(react:can): updates typescript declarations
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(eslint): fixes eslint errors
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: perf(react:can): moves prop type checks undef `if`, so they can be removed for production builds
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is patch
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: feat(react:can): adds `passThrough` option

Relates to #105
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: feat(react:can): adds `an` alias to `on` prop
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: docs(react:readme): updates examples with render children prop
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: test(react:can): covers multiple children rendering
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: feat(react:can): adds support for multiple <Can> children
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: fix(README): changes links to @casl/ability to point to npm package instead to git root [skip ci]

Fixes #102
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is patch
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  The commit should not trigger a release
[8:56:32 AM] [semantic-release] [[Function: ]] › ℹ  Analysis of 18 commits complete: minor release
[8:56:32 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: ]"
[8:56:32 AM] [semantic-release] › ℹ  The next release version is 0.8.0
[8:56:32 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "[Function: ]"
[8:56:32 AM] [semantic-release] › ✖  Failed step "generateNotes" of plugin "[Function: ]"
[8:56:32 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/home/sergii/projects/casl/node_modules/import-from/node_modules/resolve-from/index.js:11:9)
    at module.exports (/home/sergii/projects/casl/node_modules/import-from/node_modules/resolve-from/index.js:34:41)
    at module.exports (/home/sergii/projects/casl/node_modules/import-from/index.js:4:49)
    at requirePlugin (/home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/home/sergii/projects/casl/node_modules/semantic-release/lib/plugins/normalize.js:34:28)
    at pReduce (/home/sergii/projects/casl/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/sergii/projects/casl/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
{ TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/home/sergii/projects/casl/node_modules/import-from/node_modules/resolve-from/index.js:11:9)
    at module.exports (/home/sergii/projects/casl/node_modules/import-from/node_modules/resolve-from/index.js:34:41)
    at module.exports (/home/sergii/projects/casl/node_modules/import-from/index.js:4:49)
    at requirePlugin (/home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /home/sergii/projects/casl/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/home/sergii/projects/casl/node_modules/semantic-release/lib/plugins/normalize.js:34:28)
    at pReduce (/home/sergii/projects/casl/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/sergii/projects/casl/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
```

**Comment by pmowrer** [comment]
@stalniy Thanks for the report! I think this is the same issue as https://github.com/Updater/semantic-release-monorepo/issues/52. Do you mind posting [your plugin config](https://github.com/Updater/semantic-release-monorepo/issues/52#issuecomment-418232544) there?
